#!/usr/bin/env python3

import matplotlib.pyplot as plt

# Read the data from the file generated by the shell script
steps = []
with open('data.txt') as f:
    for line in f:
        step, value = line.split()
        steps.append((int(step), int(value)))

# Unpack the steps into two lists: iterations (x) and numbers (y)
x, y = zip(*steps)

# Plotting the Collatz sequence
plt.plot(x, y, marker='o')
plt.xlabel('Iterations')
plt.ylabel('Numbers')
plt.title('Collatz Sequence')
plt.grid(True)
plt.show()

